# Site settings
title: Freifunk Kassel
tagline: Das freie Bürgernetz in Kassel
author:
  name: Freifunk Kassel
  email: ffks@s01.de
  github: freifunkks
  twitter: freifunkks

permalink: /news/:title/

nav_pages:
  - title: Info
    url: /info/
  - title: News
    url: /news/
  - title: Karte
    url: /map/
  - title: Über FFKS
    url: /about/

# Build settings
exclude: ["CNAME"]
highlighter: pygments
markdown: kramdown
sass:
  sass_dir: _sass
  style: :compressed
